### ISSUE TITLE
Auto Enable for MPV Android

### ISSUE THREAD

**Issue by aeseok** [ferreum/mpv-skipsilence#1]
Hello, just trying to get this to work on MPV Android, total code noob so please help me out :). I think by default the script has to be enabled by a keybind and well I don't have access to a keyboard on the Android version of the app.

**Comment by ferreum** [comment]
I've not tried using scripts with the android app, so I can't help with that specifically. If you can set script options (`script-opts`) then you can try to set `skipsilence-enabled=yes`, which enables the script from the start. E.g. with mpv command line the equivalent option would be `--script-opts-append=skipsilence-enabled=yes`
